export const researchScenario = [
  {
    group: 'competitive_environment',
    title: 'Радиус поиска',

    fields: ['radius'],
  },
  {
    group: 'transport_infrastructure',
    title: 'Транспортная инфраструктура',
    searchable: true,
    fields: ['stops', 'parking'],
  },
  {
    group: 'social_objects' /* обязательное название */,
    title: 'Социальные объекты',
    searchable: true,
    fields: ['education', 'medicine', 'pharmacy'],
  },
  {
    group: 'commercial_objects',
    title: 'Коммерческие объекты',
    searchable: true,
    fields: ['food_shop', 'nonfood_shop', 'food', 'household', 'leisure', 'tourism', 'office', 'other'],
  },
  // {
  //   group: 'accessibility',
  //   title: 'Пешеходная и транспортная доступность',
  //   fields: ['pedestrian_accessibility', 'transport_accessibility'],
  // },
  // {
  //   group: 'demography',
  //   title: 'Демография',
  //   fields: ['population', 'population_density'],
  // },
  // {
  //   group: 'zoning',
  //   title: 'Градостроительное и ценовое зонирование',

  //   fields: ['genplan_zone', 'sub_zone', 'price_zone'],
  // },
]
export const researchFields = [
  {
    field: 'pedestrian_accessibility',
    type: 'choice',
    label: 'Выберите время пешеходной доступности',
    disabled: false,
    choices: [
      { value: 5, display_name: 5 },
      { value: 10, display_name: 10 },
      { value: 15, display_name: 15 },
      { value: 20, display_name: 20 },
      { value: 25, display_name: 25 },
      { value: 30, display_name: 30 },
      { value: 35, display_name: 35 },
      { value: 40, display_name: 40 },
      { value: 45, display_name: 45 },
      { value: 50, display_name: 50 },
      { value: 55, display_name: 55 },
      { value: 60, display_name: 60 },
    ],
  },
  {
    field: 'transport_accessibility',
    type: 'choice',
    label: 'Выберите время транспортной доступности',
    disabled: false,
    choices: [
      { value: 5, display_name: 5 },
      { value: 10, display_name: 10 },
      { value: 15, display_name: 15 },
      { value: 20, display_name: 20 },
      { value: 25, display_name: 25 },
      { value: 30, display_name: 30 },
      { value: 35, display_name: 35 },
      { value: 40, display_name: 40 },
      { value: 45, display_name: 45 },
      { value: 50, display_name: 50 },
      { value: 55, display_name: 55 },
      { value: 60, display_name: 60 },
    ],
  },
  {
    field: 'population',
    type: 'none',
    label: 'Население',
    disabled: true,
  },
  {
    field: 'stops',
    type: 'none',
    label: 'Общественный транспорт',
  },
  {
    field: 'traffic_density',
    type: 'none',
    label: 'Плотность трафика',
    disabled: true,
  },
  {
    field: 'population_density',
    type: 'none',
    label: 'Плотность населения',
    disabled: true,
  },
  {
    field: 'genplan_zone',
    type: 'none',
    label: 'ГЕНПЛАН',
    disabled: true,
  },
  {
    field: 'sub_zone',
    type: 'none',
    label: 'П33',
    disabled: true,
  },
  {
    field: 'price_zone',
    type: 'none',
    label: 'Ценовое зонирование',
    disabled: true,
  },
  {
    field: 'radius',
    type: 'choice',
    label: '',
    choices: [
      { value: 100, display_name: 100 },
      { value: 200, display_name: 200 },
      { value: 300, display_name: 300 },
      { value: 400, display_name: 400 },
      { value: 500, display_name: 500 },
      { value: 600, display_name: 600 },
      { value: 700, display_name: 700 },
      { value: 800, display_name: 800 },
      { value: 900, display_name: 900 },
      { value: 1000, display_name: 1000 },
      { value: 1100, display_name: 1100 },
      { value: 1200, display_name: 1200 },
      { value: 1300, display_name: 1300 },
      { value: 1400, display_name: 1400 },
      { value: 1500, display_name: 1500 },
      { value: 1600, display_name: 1600 },
      { value: 1700, display_name: 1700 },
      { value: 1800, display_name: 1800 },
      { value: 1900, display_name: 1900 },
      { value: 2000, display_name: 2000 },
    ],
  },
  {
    field: 'education',
    type: 'none',
    label: 'Организации учебно-воспитательного назначения',
  },
  {
    field: 'medicine',
    type: 'none',
    label: 'Медицинские организации',
  },
  {
    field: 'pharmacy',
    type: 'none',
    label: 'Аптеки и оптики',
  },
  {
    field: 'food_shop',
    type: 'none',
    label: 'Продовольственные магазины',
  },
  {
    field: 'nonfood_shop',
    type: 'none',
    label: 'Непродовольственные магазины',
  },

  {
    field: 'food',
    type: 'none',
    label: 'Предприятия питания',
  },
  {
    field: 'household',
    type: 'none',
    label: 'Предприятия бытового обслуживания',
  },
  {
    field: 'leisure',
    type: 'none',
    label: 'Объекты культурно-досуговой деятельности',
  },
  {
    field: 'tourism',
    type: 'none',
    label: 'Предприятия временного размещения',
  },
  {
    field: 'office',
    type: 'none',
    label: 'Офисы',
  },
  {
    field: 'other',
    type: 'none',
    label: 'Прочее',
  },
  {
    field: 'parking',
    type: 'none',
    label: 'Парковки',
  },
  {
    field: 'field',
    type: 'field',
    // label: 'Офисы',
    disabled: true,
  },
]
