export function useTableParams() {
  const tableParams = {
    limit: {
      label: 'Число записей в таблице',
      required: true,
      options: [
        { value: 15, display_name: '15' },
        { value: 30, display_name: '30' },
        { value: 50, display_name: '50' },
        { value: 100, display_name: '100' },
      ],
      type: 'choice',
      isCube: true,
    },
    displayedColumns: {
      label: 'Отображение столбцов',
      required: true,
      options: [
        { value: 'address_raw', display_name: 'Адрес', disabled: true },
        { value: 'object_type', display_name: 'Тип объекта' },
        { value: 'ads_type', display_name: 'Тип объявления' },
        { value: 'ne_ads_type', display_name: 'Тип объявления НЭИ' },
        { value: 'func_purpose', display_name: 'Функциональное назначение' },
        { value: 'ads_updated_internal', display_name: 'Дата изменения карточки' },
        { value: 'terms_of_sale', display_name: 'Тип предложения' },
        { value: 'is_checked', display_name: 'Проверен' },
        { value: 'ads_downloaded', display_name: 'Дата создания' },
        { value: 'date_calc', display_name: 'Дата оценки' },
        { value: 'ads_updated', display_name: 'Дата предложения' },
        { value: 'added_by', display_name: 'Создал, ФИО' },
        { value: 'modified_by', display_name: 'Обновил, ФИО' },
        { value: 'object_area', display_name: 'Площадь, кв. м.' },
        { value: 'tz_number', display_name: 'Номер ТЗ' },
        { value: 'name_by_tz', display_name: 'Наименование Объекта оценки по ТЗ' },
        { value: 'price_rent_per_m', display_name: 'Удельная арендная ставка/цена, руб. кв/м.' },
        { value: 'price_sale_per_m', display_name: 'Удельная цена, руб. за кв. м' },
        { value: 'kadast_number', display_name: 'Кадастровый номер' },
        { value: 'id', display_name: 'Идентификатор' },
        { value: 'additional_obj_id', display_name: 'Номер объекта' },
      ],
      type: 'checkbox',
      isCube: false,
    },
    sortField: {
      label: 'Сортировка по столбцу',
      required: false,
      options: [
        { value: 'address_raw', display_name: 'Адрес' },
        { value: 'object_type', display_name: 'Тип объекта' },
        { value: 'ads_type', display_name: 'Тип объявления' },
        { value: 'func_purpose', display_name: 'Функциональное назначение' },
        { value: 'ads_updated_internal', display_name: 'Дата изменения карточки' },
        { value: 'terms_of_sale', display_name: 'Тип предложения' },
        { value: 'is_checked', display_name: 'Проверен' },
        { value: 'ads_downloaded', display_name: 'Дата создания' },
        { value: 'date_calc', display_name: 'Дата оценки' },
        { value: 'ads_updated', display_name: 'Дата предложения' },
        { value: 'added_by', display_name: 'Создал, ФИО' },
        { value: 'modified_by', display_name: 'Обновил, ФИО' },
        { value: 'object_area', display_name: 'Площадь, кв. м.' },
        { value: 'tz_number', display_name: 'Номер ТЗ' },
        { value: 'name_by_tz', display_name: 'Наименование Объекта оценки по ТЗ' },
        { value: 'price_rent_per_m', display_name: 'Удельная арендная ставка/цена, руб. кв/м.' },
        { value: 'price_sale_per_m', display_name: 'Удельная цена, руб. за кв. м' },
        { value: 'kadast_number', display_name: 'Кадастровый номер' },
        { value: 'id', display_name: 'Идентификатор' },
        { value: 'additional_obj_id', display_name: 'Номер объекта' },
      ],
      type: 'choice',
      isCube: false,
    },
    sortDirection: {
      label: 'Направление сортировки',
      required: true,
      options: [
        { value: 'asc', display_name: 'По возрастанию' },
        { value: 'desc', display_name: 'По убыванию' },
      ],
      type: 'choice',
      isCube: true,
    },
  }

  return { tableParams }
}
